// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUX15x3wFQ_p57yK_TqFSpXrm-O2E7vY',
    appId: '1:1081318151334:web:45271918cc1a87678a5067',
    messagingSenderId: '1081318151334',
    projectId: 'sign-in-78f9c',
    authDomain: 'sign-in-78f9c.firebaseapp.com',
    storageBucket: 'sign-in-78f9c.firebasestorage.app',
    measurementId: 'G-4XLNQZV5RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAflItiRcc4n84QoIGwXpAAbEzENpjrIuI',
    appId: '1:1081318151334:android:ba5ba494a45ef7a28a5067',
    messagingSenderId: '1081318151334',
    projectId: 'sign-in-78f9c',
    storageBucket: 'sign-in-78f9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOuGo1oefwghiBiD-qjtmzjFuYYeDc28',
    appId: '1:1081318151334:ios:07b5e4ce8e833d938a5067',
    messagingSenderId: '1081318151334',
    projectId: 'sign-in-78f9c',
    storageBucket: 'sign-in-78f9c.firebasestorage.app',
    androidClientId: '1081318151334-p7lbl91kl5vjepb3vfehcbvi7ib4quku.apps.googleusercontent.com',
    iosClientId: '1081318151334-4m0llg8ea5tfj8qhahs4ejoobntsj40h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOuGo1oefwghiBiD-qjtmzjFuYYeDc28',
    appId: '1:1081318151334:ios:07b5e4ce8e833d938a5067',
    messagingSenderId: '1081318151334',
    projectId: 'sign-in-78f9c',
    storageBucket: 'sign-in-78f9c.firebasestorage.app',
    androidClientId: '1081318151334-p7lbl91kl5vjepb3vfehcbvi7ib4quku.apps.googleusercontent.com',
    iosClientId: '1081318151334-4m0llg8ea5tfj8qhahs4ejoobntsj40h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKUX15x3wFQ_p57yK_TqFSpXrm-O2E7vY',
    appId: '1:1081318151334:web:e4bd71b540fccfee8a5067',
    messagingSenderId: '1081318151334',
    projectId: 'sign-in-78f9c',
    authDomain: 'sign-in-78f9c.firebaseapp.com',
    storageBucket: 'sign-in-78f9c.firebasestorage.app',
    measurementId: 'G-GDX6EH0H1B',
  );
}
